catalog/urls.py
from django.urls import path
from . import views

urlpatterns=[

    path('',views.index, name='home'),
    path('create_book',views.BookCreate.as_view(),name='create_book'),
     path('create_author',views.AuthorCreate.as_view(),name='create_author'),
    path('book/<int:pk>',views.BookDetail,name='book_detail'),
    path('my_view',views.my_view,name='my_view'),
    path('signup', views.SignUpView.as_view(),name='signup'),
    path('profile/',views.CheckedOutBooksByUser.as_view(),name='profile'),
    path('list_books',views.AllBooks.as_view(),name='list_books')
]

library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('',RedirectView.as_view(url='catalog/')),
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    
]

catalog/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User  # This imports the baked in model for users

# Create your models here.
class Genre(models.Model):
    name=models.CharField(max_length=150)
    def __str__(self):
        return self.name
    
class Language(models.Model):
    name=models.CharField(max_length=200)
    def __str__(self):
        return self.name
    

class Book(models.Model):
    title=models.CharField(max_length=200)
    author = models.ForeignKey("Author",on_delete=models.SET_NULL, null=True)
    summary=models.TextField(max_length=600)
    isbn=models.CharField('ISBN',max_length=13,unique=True)
    genre=models.ManyToManyField(Genre)
    language = models.ForeignKey('Language',on_delete=models.SET_NULL,null=True)
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('book_detail',kwargs={"pk":self.pk})

class Author(models.Model):
    first_name=models.CharField(max_length=30)
    last_name=models.CharField(max_length=30)
    date_of_birth=models.DateField(null=True,blank=True)
    class Meta:
        ordering=['last_name', 'first_name']
    def get_absolute_url(self):
        #return reverse('author_detail',kwargs={"pk":self.pk})
        return reverse('list_books')
    def __str__(self):
        return f"{self.last_name}, {self.first_name}"
                       
class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True,default=uuid.uuid4)
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True,blank=True)
    borrower=models.ForeignKey(User,on_delete=models.SET_NULL, null=True,blank=True)
    
    LOAN_STATUS=(
        ('m', 'Maintenance'),
        ('o', 'On Loan'),
        ('a', 'Available'),
        ('r', 'Reserved')
    )
    status = models.CharField(max_length=1,choices=LOAN_STATUS,blank=True,default='m')
    class Meta:
        ordering = ['due_back']
    def __str__(self):
        return f"{self.id} ({self.book.title})"

catalog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse_lazy
from .models import Book,Author,BookInstance,Genre,Language
from django.views.generic import CreateView,DetailView, ListView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import get_object_or_404

# Create your views here.

def index(request):
    num_book=Book.objects.all().count()
    num_instances=BookInstance.objects.all().count()
    num_instances_avail=BookInstance.objects.filter(status__exact='a').count()
    context={
        'books':num_book,
        'inst':num_instances,
        'avail':num_instances_avail
        }

    return render(request,'catalog/index.html',context=context)


class BookCreate(LoginRequiredMixin, CreateView):
    model=Book
    fields='__all__'

class AuthorCreate(LoginRequiredMixin, CreateView):
    model=Author
    fields='__all__'

#class BookDetail(DetailView):
#    model=Book
#    inst=model.title
#    def get_context_data(self, **kwargs):
#        context =super().get_context_data(**kwargs)
#        #context['inst']=self.inst
#        context['test']="Hello Tom"
#        return context

def BookDetail(request,pk):
    #book = Book.objects.filter(pk=primary_key)
    book=get_object_or_404(Book, pk=pk)
    return render(request,'catalog/book_detail.html',context={'book':book})

@login_required
def my_view(request):
    return render(request,'catalog/my_view.html')

class SignUpView(CreateView):
    form_class=UserCreationForm
    success_url = reverse_lazy('login')
    template_name='catalog/signup.html'

class CheckedOutBooksByUser(LoginRequiredMixin,ListView):
    #list all bookinstance filtered by user session
    model=BookInstance
    template_name='catalog/profile.html'
    paginate_by=5
    
    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).all()
    
class AllBooks(ListView):
    model=Book
    template_name='catalog/list_books.html'
    paginate_by=5

    def get_queryset(self):
        return Book.objects.all()

catalog/templates/catalog/author_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
<h1>Add New Author</h1>
<form method="POST">
{% csrf_token %}
{% for field in form %}
<div class="col-6 text-start">{{field.label}}</div>
<div class="col-6">{{field}}</div>
{% endfor %}
<input type="submit" value="Submit">
</form>
</div>
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
<h1>Book Details</h1>

{{book.title}}<br/>
{{book.author}}<br/>

{{book.isbn}}<br/>
{{book.genre}}<br/>
{{lbook.anguage}}<br/>

{{book.summary}}<br/>
The ID is {{book.id}}<br/>
The test is {{test}}<br/>
<br>

{% for copy in book.bookinstance_set.all %}
{{copy.id}}<br/>
{{copy.imprint}}<br/>
{{copy.status}}<br/>
{% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/book_form.html
<h1>Create New Book</h1>
<form method="POST">
{% csrf_token %}
{{form.as_p}}
<input type="submit" value="Submit">
</form>

catalog/templates/catalog/index.html
{% extends 'base.html' %}
{% block content %}
<div class='container'>
    <h1>This is now the homepage</h1>
    <p>Total Books {{books}}</p>
    <p>Number Available {{avail}}</p> 
    {% if user.is_authenticated %}
        <p>You are logged in<br />
            Welcome: {{user.get_username}}<br/>
            <form method="post" action="{% url 'logout' %}?next={{request.path}}">
                {% csrf_token %}
                <input type="submit" value="Log Out">
            </form>
    {% else %}
            <p>You are not logged in<br/>
            <a href="{% url 'login' %}?next={{request.path}}">click here to log in</a>
    {% endif %}
</div>
{% endblock %}

catalog/templates/catalog/list_books.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1>Listing all books in system</h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">ISBN</th>
                <th scope="col">Title</th>
                <th scope="col">Author</th>
                <th scope="col">Genre</th>
                <th scope="col">Langage</th>
            </tr>
        </thead>
    {% for book in book_list %}
    <tr>
   <td scope="'row"><a href="book/{{book.id}}">{{book.isbn}}</a></td>
   <td scope="'row">{{book.title}}</td>
   <td scope="'row">{{book.author}}</td>
   <td scope="'row">{{book.genre}}</td>
   <td scope="'row">{{book.language}}</td>
    </tr> 
   {% endfor %}
    </table>
</div>
{% endblock %}

catalog/templates/catalog/my_view.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>You should be logged in to see this content - if you're not, you are a bad actor and a very bad man</h1>
</body>
</html>

catalog/templates/catalog/profile.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
 <h1>Here are the books you have checked out</h1>
 <ol>
 {% for book in bookinstance_list %}
<li>{{book}}</li>
 {% endfor %}
</ol>
</body>
</html>

catalog/templates/catalog/signup.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Register New User</h1>
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Register">



    </form>
</body>
</html>

templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>Base</title>
</head>
<body>
<!--Nav Bar-->
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link" href="{% url 'list_books' %}">List</a>
          <a class="nav-link" href="{% url 'create_book' %}">Add Book</a>
          <a class="nav-link" href="">Delete</a>

        </div>
      </div>
    </div>
  </nav>

{% block content %}
{% endblock  %}
</body>
</html>